version: '3.8'

services:
  web:
    build: .
    container_name: bilet-platform
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
    networks:
      - bilet-network

networks:
  bilet-network:
    driver: bridge